name: Analysis

on:
  push:
    branches:
      - "main"
      - "[0-9].*"
  pull_request:

jobs:
  phpstan:

    name: PHPStan
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout changes
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.*') }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php-version }}-
            composer-${{ runner.os }}-
            composer-

      - name: Download dependencies
        run: |
          composer install --no-interaction --no-progress --optimize-autoloader --no-scripts

      - name: Run PHPStan
        run: |
          ./vendor/bin/phpstan --no-progress
